In [1]:
#!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/20201.ai4eng/master/init.py
import init; init.init(force_download=False); init.get_weblink()


endpoint https://m5knaekxo6.execute-api.us-west-2.amazonaws.com/dev-v0001/rlxmooc


In [2]:
import inspect
from local.lib.rlxmoocapi import session
student = session.Session(init.endpoint).login( course_id=init.course_id, 
                                                session_id="UDEA", 
                                                lab_id="L01.01" )

username: kevin.martinez@udea.edu.co
password: ········


### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     
_Sugerencia_: completa el código de la siguiente manera:

    def suma_matrices(a,b):
       ## --- TU CODIGO AQUI ---
       result = a + b
       return result

In [3]:
def suma_matrices(a,b):
    ## --- TU CODIGO AQUI ---
    result = a + b
    return result

comprueba manualmente tu código

In [4]:
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print (a)
print (b)
print (suma_matrices(a,b))

[[3 3]
 [4 7]
 [4 4]]
[[1 2]
 [0 9]
 [9 9]]
[[ 4  5]
 [ 4 16]
 [13 13]]


#### registra tu solución en línea

In [9]:
student.submit_task(globals(), task_id="task_01");

### Ejercicio 2: Realiza un cálculo 

En este ejercicio, al ejecutar la celda de más abajo, se generará una lista de número aleatorios.

Tendrás que calcular el valor promedio de la lista y asignarlo a la variable `avg` más abajo.

Puedes usar el método que quieras para realizar el cálculo (a mano, excel, python, etc.) lo que importa es el valor que obtengas.


In [6]:
import numpy as np
rlist = np.random.randint(100, size=10)
rlist

array([31, 23, 31, 21, 24, 63, 41, 84, 83, 46])

#### tu solución

In [7]:
avg = np.mean(rlist)

#### registra tu solución en línea

In [8]:
student.submit_task(globals(), task_id="task_02");